### ISSUE TITLE
Include requested Blueprints in AST of program

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#17]
current builds that generate functions in javascript may generate these functions each time certain conditions are repeated, instead of just once (preferably at the top or otherwise some logical point in the target-language code. Some examples may include

Generating a blueprint each time construct is called.
Generating a __factorial function each time factorial `'~!` is used

This will get a fix in the future, probably not before turn-in though

**Comment by jadengore** [comment]
Let's close this. Blueprints are going to be removed from the language going forward anyways.
