### ISSUE TITLE
Differentiation between subtraction and negative numbers

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#20]
Currently, the scanner prioritizes capturing negative numbers over a subtraction operation. This means that in order to do subtraction, one must either put a space before the numlit, or wrap the numlit. 

Consider:
`i < a["length"]-1`
which parses to:
`i`, `<`, `a`, `[`, `STRLIT("length")`, `]`, `NUMLIT(-1)`
This is a syntax error as an int lit cannot follow an indexed variable without some sort of binary operator. In order to fix this, one needs to write:
`i < a["length"] - 1` (with space)
or `i < a["length"]-(1)` (ugly, don't pls)

Currently open for suggestions. The main option now is to realize that a subtraction operation must be made distinct from a numlit by adding a (non-optional) space.

**Comment by jadengore** [comment]
I actually remember modifying the code so that if a - is found, we fall into NUMLIT tokenization. We had the opposite problem where it was parsing as a subtraction binary expression rather than a NUMLIT. Can't remember the example, but I'll look for the commit.

**Comment by jadengore** [comment]
Yeah, so no real commit, just because our grammar is a CFL this is occurring. Difficult issue. Take a look [here](https://github.com/AuthorOfTheSurf/KobraScript/blob/master/scanner.js#L160)

**Comment by AuthorOfTheSurf** [comment]
Yup, we definitely need to parse numlit before single char tokens i.e. subtraction. The issue here is we need some parsetime context:

try to do:
`a["length"]-1` --->  `a`, `[`, `STRLIT("length")`, `]`, `NUMLIT(-1)`
if there is an unexpected numlit error, AND the numlit is negative, try to mitigate the error by re-tokenizing the numlit as a subtraction:
`a`, `[`, `STRLIT("length")`, `]`, `-`, `NUMLIT(1)`

That would be the solution if we want to allow `-` to be used without spaces. Would work recursively if there are multiple negative numlits in a row:

`a["length"]-1-1-1`
--->  `a`, `[`, `STRLIT("length")`, `]`, `NUMLIT(-1)`, `NUMLIT(-1)`, `NUMLIT(-1)` (syn err)
--->  `a`, `[`, `STRLIT("length")`, `]`, `-`, `NUMLIT(1)`, `NUMLIT(-1)`, `NUMLIT(-1)` (syn err)
--->  `a`, `[`, `STRLIT("length")`, `]`, `-`, `NUMLIT(1)`, `-`, `NUMLIT(1)`, `NUMLIT(-1)` (syn err)
--->  `a`, `[`, `STRLIT("length")`, `]`, `-`, `NUMLIT(1)`, `-`, `NUMLIT(1)`, `-`, `NUMLIT(1)` (OK)

We have to consider if such an action could have unexpected consequences. I don't see anything at the moment. We only do the token coercion if there would be a syntax error and this only needs to be done in the case of the `-` operator, not all binary operators.

**Comment by AuthorOfTheSurf** [comment]
Closing this. Addition and subtraction operations should always have a space a la [PEP 8](https://www.python.org/dev/peps/pep-0008/#other-recommendations).

**Comment by jadengore** [comment]
:+1:
