### ISSUE TITLE
Allow anon without parens if there are no arguments

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#21]
Currently `()` is required even on an `anon` function that has no parameters. Make a syntax adjustment to allow such a function to be called without the parens if there are no arguments.

So allow:
```
anon:
    $ x = {}
    return x
end
```
where
```
anon():
    $ x = {}
    return x
end
```
is required

**Comment by jadengore** [comment]
Not only added this to the language, but improved arguments to the anonymous function.
