### ISSUE TITLE
Redo `anon` to a statement/literal structure that better suggests closure

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#34]
The popular anonymous self calling function is a nifty feature of KS. However it still takes on it's name from JavaScript which in itself is a phrase that describes a closure. (functional scope + can put variables into the function and invoke it).

As such we would like to improve KobraScript's `anon` statement by making more prominent, clear, and closure-suggestive.

Here is some proposal code that makes a simple incrementing closure after being supplied a starting value:

    $ startingValue = 10

    $ incrementer = closure(startingValue):
      $ x = startingValue

      return {
        increment: fn():
          return x += 1
        ..,
        decrement: fn():
          return x -= 1
        ..,
        zero: fn():
          return x = 0
        ..
      }
    end

    $ incrementer = |startingValue|:
      $ x = startingValue

      return {
        increment: fn():
          return x += 1
        ..,
        decrement: fn():
          return x -= 1
        ..,
        zero: fn():
          return x = 0
        ..
      }
    end

    $ incrementer = close{ startingValue as s }:
      $ x = s

      return {
        increment: fn():
          return x += 1
        ..,
        decrement: fn():
          return x -= 1
        ..,
        zero: fn():
          return x = 0
        ..
      }
    end

Currently liking the final version that uses curly braces (in a Go-like way) to suggest that this is strictly a different structure than a function. `close(x,y)` does not suggest this as this is function syntax. I'm also liking the variable rename that the third example shows too, it shows the relation between the argument and it being used as a parameter.

**Comment by jadengore** [comment]
Working on this. Currently we are going with this syntax:

```sh
$ incrementer = close{s}:
  $ x = s

  return {
    increment: fn():
      return x += 1
    ..,
    decrement: fn():
      return x -= 1
    ..,
    zero: fn():
      return x = 0
    ..
  }
end
```
