### ISSUE TITLE
Current generation implementation does not allow expressions to be braced

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#43]
See title. Previously we used to just put braces around every expression that was generated. However this isn't the best practice as there are extra characters laying around, and sometimes code-formatting goes a bit hay-wire e.g. putting an expression after an object literal would stick the two together.

Suggestion: keep track of expressions that have been intentionally braced and generate them that way.

**Comment by rtoal** [comment]
What to you mean by “keep track of”?

Stuff like this should he handled in the syntax, so revisit the grammar. “Keep track of” sounds like a semantic action.

On Jul 17, 2015, at 9:18 AM, Zane <notifications@github.com<mailto:notifications@github.com>> wrote:


See title. Previously we used to just put braces around every expression that was generated. However this isn't the best practice as there are extra characters laying around, and sometimes code-formatting goes a bit hay-wire e.g. putting an expression after an object literal would stick the two together.

Suggestion: keep track of expressions that have been intentionally braced and generate them that way.

**Comment by AuthorOfTheSurf** [comment]
The syntax allows it as a braced expression is also a type of expression. I say keep track of because this notion is lost at the parser level:

```JavaScript
} else if (at('(')) {
  match('(')
  var expression = parseExpression()
  match(')')
  return expression
}
```

As you can see, when the parser is parsing a braced Expression the notion of the parsed expression being braced is lost. The expression entity produced is indifferent of whether it was braced in KS.

**Comment by jadengore** [comment]
This was also some code before we started moving KS towards a transpiler correct?

**Comment by AuthorOfTheSurf** [comment]
Yes, the parser was improved in several parts but expression parsing wasn't really touched except for adding in `new`.

**Comment by jadengore** [comment]
:+1: Is this a task on PR?

**Comment by AuthorOfTheSurf** [comment]
Not yet, I am working on return-related changes currently.
