### ISSUE TITLE
[KEP] Implicit return

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#46]
- Improves conciseness of lines by making them shorter
- `return` is 6 characters long, making it the longest used (sorry `continue`) statement token in KS. Returning a value is very common to boot.
- Makes single line functions way nicer:
```$ double = fn(n) -> 2*n```
- Shortening the `return` keyword in some way *is* an option, but making it optional in certain cases is better.
- Looks very good in KS, which has short lines
- Possibly my favorite Ruby feature, really started to like it when I worked with [Crystal](https://github.com/manastech/crystal)

Spec:
  - Expression is final expression of block
  - Block was a subroutine
  - Ideas for convention: Makes naming the return value early look really good.
```
{
  "json": fn():
    $ res = { "message": "Hello, World" }
    res.headers["Content-type"] = 'application/json'
    res
  end
}
```

**Comment by jadengore** [comment]
I think we should give this some more thought. My natural instinct is to say have optional implicit return, but I think it may actually be a bad decision to do that. Should be an all or nothing type of deal.

I'd encourage you to read [this discussion/suggestion](https://github.com/jashkenas/coffeescript/issues/2477) recommending Coffeescript adopt implicit returns.

**Comment by AuthorOfTheSurf** [comment]
Took a look and some of the commenters in there make good points. I personally think that KobraScript has a syntax that would suit implicit return better than CS. This is similar to why I like it in Ruby/Crystal.

I think that implicit return could still work, but that we should make it more clear in some way. This would be keeping with the KobraScript philosophy of signaling what is going on early. Here's my idea:

1) Signal the return value in the function definition. The name would then be implicitly declared. Perhaps we allow assignment here. Then, if any statement-expression is just the name itself it gets implicitly returned as intended. This would be Go-like in that you cannot redeclare the variable, as it has already been declared. The benefit is JS allows us to go from `undefined` to a value easily.

```JavaScript
{
  'json': fn() res:
    res = { 'message': 'Hello, World' }
    res.headers['Content-type'] = 'application/json'
    res
  end
}
```

```JavaScript
{
  "json": function() {
    var res;
    res = { "message": "Hello, World" };
    res.headers["Content-type"] = "application/json";
    return res;
  }
```
I kind of like it, thoughts? It's even safer than "last statement in function". Plus it shows intent, from the first line you can tell exactly what's going on:
```JavaScript
  "json": fn() res:
```
a) Returns a `json` `res`ponse
b) Look especially to see what is done with the `res` variable in this function
c) No parameters, so probably a static response

**Comment by jadengore** [comment]
So, what I'm seeing is less of the idea of implicit return language-wide, but more of the convenience of it in a web framework in this one example. However, most frameworks, even Koa, don't "return" a response. `res.send()` in Express, `reply()` in Hapi. Most handlers in your example above won't even benefit from implicit return.

I could see the benefit of an implicit return, but the problem is that we are ultimately transpiling to Javascript, and your example depends on Javascript frameworks that pretty much would never benefit from implicit return. Your example above makes a lot of sense. I just don't see implicit return as a common enough use case that it would benefit.

**Comment by AuthorOfTheSurf** [comment]
The purpose of implicit return is to get rid of the wordy-ness of `return`. Whether or not web frameworks use return is another story—I was just trying to come up with an example that made sense.

JavaScript is a functional language like KobraScript. If the programmer knows what value he/she wants to return, then why make it more verbose then it needs to be? If the current verbosity of `return` isn't a problem (valid), then that is a different argument.

**Comment by jadengore** [comment]
I don't think `return` is too verbose. I really think this should be one of those things we keep. I think that while a longer keyword, I don't find it impossibly long, and it **explicitly** shows where the function exits when a value is expected. 

I also read up some more on explicit vs implicit returns in Ruby [in this article](http://blog.nerdbucket.com/the-horrible-cost-of-using-explicit-returns-in-ruby/article). While this article mostly talks about performance differences specific to Ruby, I wrote his example in Kobrascript w/ explicit and implicit return to show how implicit return can lead to very unclear blocks of code, especially with multiple conditionals.

KS w/ implicit return:
```sh
fn comparison(a, b):
  if (a < b):
    -1
  .. else if (a > b):
    1
  .. else
    0
  end
end
```

KS w/ explicit return:
```sh
fn comparison(a, b):
  if (a < b):
    return -1
  .. else if (a > b):
    return 1
  .. else
    return 0
  end
end
```

KobraScript also had a huge design goal of becoming more readable (`..` syntax for conditional statements is one of my favorite things in KS, and makes things way more readable). Implicit return here clearly makes things way more nebulous.

**Comment by AuthorOfTheSurf** [comment]
That is a good example. It is regrettable that `return` is long, but not too bad as you noted. `return` is clear, and will be improved by same-line enforcement + the `leave` statement.
