### ISSUE TITLE
[Review] `is` operator implementation

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [AuthorOfTheSurf/KobraScript#54]
How `is` is currently generated:
```JavaScript
  if (lexeme === 'is') {
    js = util.format('(typeof %s === typeof %s)', left, right)
  }
```

Is this useful? What about constructors?
`left.constructor.name === right.constructor.name`

This is how one would have to check if a variable is a string (using a literal):
```JavaScript
$ x = "time"
say x is ""
```

I am not liking what I am seeing, review time.

**Comment by rtoal** [comment]
What the heck is an "IS STATEMENT"? I don't see any statements here. Are you talking about an operator? An expression? Why did you call it a "statement"? I'm confused.

**Comment by AuthorOfTheSurf** [comment]
Whoops, the `is` operator, so expression. I stand corrected.

**Comment by rtoal** [comment]
Okay I will delete my comment after you edit it.

On Jul 19, 2015, at 8:25 PM, Zane <notifications@github.com<mailto:notifications@github.com>> wrote:


Whoops, the is operator, so expression. I stand corrected.

**Comment by AuthorOfTheSurf** [comment]
Suggestions:

1) Just implement [typeof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) instead.
2) Implement it following the same pattern as `typeof`:
```
SomeEntity is 'function'
x is 'number' // a little troubling as in KS there is no "number"
```
```
typeof SomeEntity === 'function'
typeof x === 'number'
```
3) Remove it

**Comment by AuthorOfTheSurf** [comment]
The `is` operator now has the correct `typeof` pattern.
