### ISSUE TITLE
2.2.2?

### ISSUE THREAD

**Issue by rtoal** [AuthorOfTheSurf/KobraScript#68]
Will there be a 2.2.2 or a 2.3 or a 3.0 release in the near future?

**Comment by ebramanti** [comment]
@rtoal Believe 2.3 is in progress, we want to revamp the CLI.

**Comment by AuthorOfTheSurf** [comment]
KobraScript development is ongoing, 2.3 will be the next release.

**Comment by AuthorOfTheSurf** [comment]
Might have to jump to KS 3.0:
- Incorporate ES 6 features such as lambdas and `const` declarations (i.e. the sweet good stuff)
- Upgrade code of compiler. 3.0 might be written with an ES6 compiler, so may no longer work in a es5 environment. I think this is ok. Compiler lang and output lang will both be ES6 JS.

Should be fun!

**Comment by AuthorOfTheSurf** [comment]
[We are jumping to KS 3.0 folks]( https://github.com/AuthorOfTheSurf/KobraScript/issues/69 )
